### ISSUE TITLE
C3_Client_V3::create_credentials() が EC2 Role を使わない

### ISSUE THREAD

**Issue by wokamoto** [amimoto-ami/c3-cloudfront-clear-cache#20]
C3_Client_V3::create_credentials() で、c3_settings を読み込んで credentials を組み立ててるけど c3_settings に access_key, secret_key が入っていることを前提にしているため、EC2 Role を使用したい時に distribution_id のみ入ってる場合に正常に credential が生成されません。

```
$credentials = array(
	'credentials' => array(
		'key'    => esc_attr( $c3_settings['access_key'] ),
		'secret' => esc_attr( $c3_settings['secret_key'] ),
	),
);
```

こんな感じで isset() されてて empty() じゃなければ $credentials array を作るようにしたほうがいいんじゃないかな？

```
$credentials = array();
if ( isset($c3_settings['access_key']) && isset($c3_settings['secret_key']) && ! empty($c3_settings['access_key']) && ! empty($c3_settings['secret_key']) ) {
	$credentials = array(
		'credentials' => array(
			'key'    => esc_attr( $c3_settings['access_key'] ),
			'secret' => esc_attr( $c3_settings['secret_key'] ),
		),
	);
}
```

**Comment by hideokamoto** [comment]
v3のソース、今使ってないんです（理由はちょっと失念）。

managedでコケる原因判明したので、パッチ作成済みです。
https://github.com/amimoto-ami/c3-cloudfront-clear-cache/pull/24
