### ISSUE TITLE
Using EC2 Roles Fails

### ISSUE THREAD

**Issue by Juberstine** [amimoto-ami/c3-cloudfront-clear-cache#21]
I noticed in your release notes it says roles were added in 2.2.0. That said, If I try to just add the distro ID and then click the button to perform an invalidation, it just errors saying secret key not set. Can you provide more insight on how to use this with roles? We have added the roles for the machines to support invalidations but it's not working.

**Comment by hideokamoto** [comment]
Please try the policy.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "cloudfront:GetDistribution",
                "cloudfront:ListInvalidations",
                "cloudfront:GetStreamingDistribution",
                "cloudfront:GetDistributionConfig",
                "cloudfront:GetInvalidation",
                "cloudfront:CreateInvalidation"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```
