### ISSUE TITLE
PHP Fatal error:  Cannot redeclare Aws\constantly()

### ISSUE THREAD

**Issue by wokamoto** [amimoto-ami/c3-cloudfront-clear-cache#29]
他のプラグインで aws SDK をインクルードしていると以下のエラーが出ます。

```
PHP Fatal error:  Cannot redeclare Aws\constantly() (previously declared in /var/www/html/wp-content/plugins/amazon-polly/vendor/aws/Aws/functions.php:19) in phar:///var/www/html/wp-content/plugins/c3-cloudfront-clear-cache/libs/aws.v3.phar/Aws/functions.php on line 22
```

**Comment by wokamoto** [comment]
pr 出しました。
https://github.com/amimoto-ami/c3-cloudfront-clear-cache/pull/30

**Comment by hideokamoto** [comment]
ありがとうございます！
ただ、他のプラグインのsdkを使う場合にv2かv3かどっちをincludeしてるか判定しないといけないのがつらいですね。。。

ちょっと組み合わせテストやってみます。
@wokamoto

**Comment by hideokamoto** [comment]
- 他のプラグインから先にロードされてる場合はそっちをつかう
- v2のpharきた時はそっちで動くようにする
- latestのCloudFront api叩く

これで一旦マージ

**Comment by wokamoto** [comment]
ver.5.3.3  で解決したようなので Close します
