### ISSUE TITLE
AWS Keys in wp-config

### ISSUE THREAD

**Issue by alloylab** [amimoto-ami/c3-cloudfront-clear-cache#35]
Is it possible to define the AWS keys in the wp-config file? Thanks.

**Comment by hideokamoto** [comment]
Thanks for waiting for a long time.
We've released version 6.1.1. to support this feature.

We can set AWS keys like these PHP codes onto `wp-config.php`.

```
define( 'AWS_ACCESS_KEY_ID', '' );
define( 'AWS_SECRET_ACCESS_KEY', '' );
define( 'C3_DISTRIBUTION_ID', '' );
```

Thanks!
