### ISSUE TITLE
Purge doesn't work

### ISSUE THREAD

**Issue by kasinobonuksia** [amimoto-ami/c3-cloudfront-clear-cache#41]
Plugin used to work perfectly. Has stopped working sometime in the last month. Error below.

C3 Invalidation Error : Error executing "CreateInvalidation" on "https://cloudfront.amazonaws.com/2017-10-30/distribution/EQSV3SDRMJ1TT/invalidation"; AWS HTTP error: Client error: `POST https://cloudfront.amazonaws.com/2017-10-30/distribution/EQSV3SDRMJ1TT/invalidation` resulted in a `403 Forbidden` response: <?xml version="1.0"?> <ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2017-10-30/"><Error><Type>Sender</Type>< (truncated...) SignatureDoesNotMatch (client): Signature expired: 20190929T171351Z is now earlier than 20190929T171436Z (20190929T171936Z - 5 min.) - <?xml version="1.0"?> <ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2017-10-30/"><Error><Type>Sender</Type><Code>SignatureDoesNotMatch</Code><Message>Signature expired: 20190929T171351Z is now earlier than 20190929T171436Z (20190929T171936Z - 5 min.)</Message></Error><RequestId>4fea0fbe-e2dd-11e9-b6f8-1d511a8a52fe</RequestId></ErrorResponse>

**Comment by hideokamoto** [comment]
Are you put a valid AWS Access Key and AWS Secret Key?

And could you check the server timezone?

AWS API using the server data time.

> AWS products validate credentials for proper scope; the credential parameter must specify the correct service, Region, and date.
> https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html#signature-v4-troubleshooting-credential-scope

So sometimes, when the server timezone is invalid, the AWS API will return error.
