### ISSUE TITLE
I get a fatal error when running "Flush All CDN Cache".

### ISSUE THREAD

**Issue by torounit** [amimoto-ami/c3-cloudfront-clear-cache#50]
I get a fatal error when running "Flush All CDN Cache".

Fatal error: Uncaught Error: Class 'C3_Invalidation' not found in /var/www/vhosts/www.hwtest.dev/wp-content/plugins/c3-cloudfront-clear-cache/c3-cloudfront-clear-cache.php:222
--
  | Stack trace:
  | #0 /var/www/vhosts/www.hwtest.dev/wp-content/plugins/amimoto-dashboard/module/model/c3.php(153): CloudFront_Clear_Cache->c3_invalidation()
  | #1 /var/www/vhosts/www.hwtest.dev/wp-content/plugins/amimoto-dashboard/amimoto-plugin-dashboard.php(141): Amimoto_C3->invalidation('all')
  | #2 /var/www/vhosts/www.hwtest.dev/wp-includes/class-wp-hook.php(287): Amimoto_Dash->update_settings('')
  | #3 /var/www/vhosts/www.hwtest.dev/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
  | #4 /var/www/vhosts/www.hwtest.dev/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
  | #5 /var/www/vhosts/www.hwtest.dev/wp-admin/admin.php(175): do_action('admin_init')
  | #6 {main}
  | thrown in /var/www/vhosts/www.hwtest.dev/wp-content/plugins/c3-cloudfront-clear-cache/c3-cloudfront-clear-cache.php on line 222

**Comment by hideokamoto** [comment]
Is the `c3 cloudfront clear cache` plugin acticvated?

**Comment by torounit** [comment]
I enabled c3 cloudfront clear cache and that solved the problem.
