### ISSUE TITLE
SameSite Cookie Policy change will be required

### ISSUE THREAD

**Issue by svandragt** [amimoto-ami/c3-cloudfront-clear-cache#53]
Just wanted to notify that there are recently SameSite Cookie Policy changes, that apply to this plugin

>Cookies with SameSite=None must now also specify the Secure attribute (they require a secure context/HTTPS).
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Feel free to look at the patch for my fork.
* https://github.com/humanmade/c3-cloudfront-clear-cache/pull/6
* https://github.com/humanmade/c3-cloudfront-clear-cache/commit/cc707736ba1a13e994191f08cc2317a66e96a001.patch

You might have to adapt the patch to use the older `setcookie()` argument definition as this patch is based on a fork that drops support for PHP7.2 and older.

**Comment by hideokamoto** [comment]
Thanks for the important information!
We've published a new version(6.1.1) and it will support the new cookie policy!

https://github.com/amimoto-ami/c3-cloudfront-clear-cache/blob/master/classes/WP/Fixtures.php#L85-L129
