### ISSUE TITLE
setcookie() の引数がおかしいです。

### ISSUE THREAD

**Issue by wokamoto** [amimoto-ami/c3-cloudfront-clear-cache#68]
https://github.com/amimoto-ami/c3-cloudfront-clear-cache/blob/2578d1deaff61c1d82995b96b7920ac55cf9d850/classes/WP/Fixtures.php#L56-L65

第3引数は array() ではなくて integer のはずです。
https://www.php.net/manual/ja/function.setcookie.php

**Comment by hideokamoto** [comment]
7.3からはいけるのでは。
@wokamoto @wo

**Comment by wokamoto** [comment]
7.2 以前の環境も残ってるので、後方互換残してください。
@hideokamoto 

```
if ( version_compare( "7.3.0", phpversion(), ">=" ) ) {
  	// PHP 7.3.0 or higher
  	setcookie( 
 	 	C3_AVOID_CACHE_COOKIE_KEY, 
 	 	time(), 
 	 	array( 
 		 	'expires'  => 0, 
 		 	'samesite' => 'None', 
 		 	'secure'   => true, 
 		 	'path'     => $cookie_path, 
 	 	) 
  	); 
 } else {
	// Less than PHP 7.3.0
	setcookie( 
 		C3_AVOID_CACHE_COOKIE_KEY, 
 		time(),
 		0,
 		 $cookie_path,
 		 '',
 		 true,
 		 true
 	); 
 }
 ```

**Comment by wokamoto** [comment]
この issue に対する PR 作っておいたので、確認お願いします。
https://github.com/amimoto-ami/c3-cloudfront-clear-cache/pull/69
